version: '3'

services:

  redis:
    image: 'redis:5.0.6'
    command: redis-server 
    volumes:
      - 'redis:/data'

  website:
    depends_on:
      - 'redis'
    build: .
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'redis'
    build: .
    command: sidekiq 
    volumes:
      - '.:/app'
    env_file:
      - '.env'


volumes:
  redis:
